project:
  type: website
  output-dir: docs

website:
  title: "Bianca Rodas ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: portfolio-final.qmd
        text: "Demo"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

